export const SubjectEnum = {
    GEOGRAPHY: 'GEOGRAPHY',
    HISTORY_OF_UKRAINE: 'HISTORY_OF_UKRAINE',
    UKRAINIAN_LANGUAGE: 'UKRAINIAN_LANGUAGE',
    UKRAINIAN_LITERATURE: 'UKRAINIAN_LITERATURE',
    MATHEMATICS: 'MATHEMATICS',
    ENGLISH: 'ENGLISH',
    BIOLOGY: 'BIOLOGY',
    PHYSICS: 'PHYSICS',
    CHEMISTRY: 'CHEMISTRY'
}

export const TestsEnum = {
    MULTI_ANSWER: 'MULTI_ANSWER',
    SINGLE_ANSWER: "SINGLE_ANSWER",
    BOOLEAN: 'BOOLEAN',
    ACCORDANCE: 'ACCORDANCE'
}
